config/routes.rb
Agents::Application.routes.draw do
  
  resources :cars

  devise_for :users
  resources :users
  
  resources :agents

  match 'users/edit/:id' => 'users#edit'
  get "home/index"

  resources :order_types 
  resources :orders do
    collection do
      get 'showmy'
    end
  end
  resources :contacts do
    collection do 
      get 'getcsv'
      get 'getcsvfororder'
      get 'showbyorder'
      get 'showbystatus'
      get 'todays'
    end
   

    
      
  end
match 'orders/for_order_types/:id', :controller=>'orders', :action => 'for_order_types'
match 'orders/get_criteria_for/:id', :controller=>'orders', :action => 'get_criteria_for'
  
match 'leads/showbyorder/:id' =>  'leads#showbyorder'

   root :to => "home#index"

end

app/controllers/order_types_controller.rb
class OrderTypesController < ApplicationController
  load_and_authorize_resource

  # GET /order_types
  # GET /order_types.xml
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @order_types }
    end
  end

  # GET /order_types/1
  # GET /order_types/1.xml
  def show
    @order_types = OrderType.all
     
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order_type }
    end
  end

  # GET /order_types/new
  # GET /order_types/new.xml
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order_type }
    end
  end

  # GET /order_types/1/edit
  def edit
  end

  # POST /order_types
  # POST /order_types.xml
  def create

    respond_to do |format|
      if @order_type.save
        format.html { redirect_to(@order_type, :notice => 'Order type was successfully created.') }
        format.xml  { render :xml => @order_type, :status => :created, :location => @order_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /order_types/1
  # PUT /order_types/1.xml
  def update

    respond_to do |format|
      if @order_type.update_attributes(params[:order_type])
        format.html { redirect_to(@order_type, :notice => 'Order type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /order_types/1
  # DELETE /order_types/1.xml
  def destroy

    @order_type.destroy

    respond_to do |format|
      format.html { redirect_to(order_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/order_types/_form.html.erb
<%= form_for(@order_type) do |f| %>
  <% if @order_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_type.errors.count, "error") %> prohibited this order_type from being saved:</h2>

      <ul>
      <% @order_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_types/edit.html.erb
<h4>Editing order type</h4>

<%= render 'form' %>

<%= link_to 'Show', @order_type %> |
<%= link_to 'Back', order_types_path %>

app/views/order_types/index.html.erb
<h4>Listing order types</h4>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    	
  </tr>

<% @order_types.each do |order_type| %>
  <tr>
    <td><%= order_type.name %></td>
    <td><%= link_to 'Show', order_type %></td>
    <td><%= link_to 'Edit', edit_order_type_path(order_type) %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order type', new_order_type_path %>

app/views/order_types/new.html.erb
<h4>New order type</h4>

<%= render 'form' %>

<%= link_to 'Back', order_types_path %>

app/views/order_types/show.html.erb
<p id="notice"><%= notice %>
  <b>Name:</b>
  <%= @order_type.name %>
</p>

<h3>Existing order types</h3>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_types.each do |order_type| %>
  <tr>
    <td><%= order_type.name %></td>
    <td><%= link_to 'Show', order_type %></td>
    <td><%= link_to 'Edit', edit_order_type_path(order_type) %></td>
    <td><%= link_to 'Destroy', order_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Edit', edit_order_type_path(@order_type) %> |
<%= link_to 'Back', order_types_path %>